<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.30">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TrainingProjectShop.Application\TrainingProjectShop.Application.csproj" />
    <ProjectReference Include="..\TrainingProjectShop.Domain\TrainingProjectShop.Domain.csproj" />
    <ProjectReference Include="..\TrainingProjectShop.Infrastructure\TrainingProjectShop.Infrastructure.csproj" />
  </ItemGroup>

</Project>
